name: Deploy

on:
  push:
    branches:
      - 'master'

env:
  CLUSTER_NAME: 'kubernetes-ruby-demo-cluster'
  CLUSTER_RESOURCE_GROUP: 'kubernetes-ruby-demo-rg'
  NAMESPACE: 'default'
  APP_NAME: 'kubernetes-ruby-demo-app-name'

jobs:
  k8s:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push docker image - AppX
      uses: docker/build-push-action@v2
      with:
        context: ./appX
        file: ./appX/Dockerfile
        push: true
        tags: pedrofurtado/kubernetes-ruby-demo-appx:${{ github.sha }}
    -
      name: Build and push docker image - AppY
      uses: docker/build-push-action@v2
      with:
        context: ./appY
        file: ./appY/Dockerfile
        push: true
        tags: pedrofurtado/kubernetes-ruby-demo-appy:${{ github.sha }}
    -
      name: Build and push docker image - AppZ
      uses: docker/build-push-action@v2
      with:
        context: ./appZ
        file: ./appZ/Dockerfile
        push: true
        tags: pedrofurtado/kubernetes-ruby-demo-appz:${{ github.sha }}

    - 
      name: Azure AKS - Set context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - 
      name: Azure AKS - Create namespace
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

    - 
      name: Azure AKS - Deploy to k8s
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/azure.yml
        namespace: ${{ env.NAMESPACE }}
